### ISSUE TITLE
Equation 63 forward Euler

### ISSUE THREAD

**Issue by olivierbonte** [ODINN-SciML/DiffEqSensitivity-Review#105]
When I apply the multivariate Taylor approximation on the first part on equation 63 (section 3.9.4), I get:
$u^{t+1} + s^{t+1}\epsilon = u^t +  s^t  \epsilon + \Delta t  f (u^t + s^t \, \epsilon, \theta + \epsilon, t) = u^t + s^t \epsilon + \Delta t (f(u^t,\theta,t)  + \frac{\partial f}{\partial u}s^t \epsilon + \frac{\partial f}{\partial \theta}\epsilon)$
In the paper however we get:
$u^t + f(u^t,\theta,t)  + \Delta t(\frac{\partial f}{\partial u}s^t + \frac{\partial f}{\partial \theta})\epsilon$
So I was wondering here how or why the $\Delta t$ before $f(u^t,\theta,t)$ went out and why $s^t \epsilon$ is dropped. Maybe I am missing something (obvious) here, so feel free to point out any mistake in my reasoning above.

**Comment by facusapienza21** [comment]
Thank you so much @olivierbonte for pointing this out. Yes, indeed there is a mistake in the original calculation, missing two terms here. This is the correct formula:
![image](https://github.com/ODINN-SciML/DiffEqSensitivity-Review/assets/39526081/8b6fc28c-0077-4049-98dc-8bf6b930145f)
You didn't miss anything, I did ;)

**Comment by olivierbonte** [comment]
No problem, glad to help :) 
I made a pull request to adapt the equation as you proposed!
