### ISSUE TITLE
A better name for this repository? 

### ISSUE THREAD

**Issue by facusapienza21** [ODINN-SciML/DiffEqSensitivity-Review#24]
The name `review-diffeq-gradient`  does not sounds very appealing...  Another options are `review-sensitivity-methods`, `DiffEqSensitivity-review`, ... any suggestion @JordiBolibar ?

**Comment by JordiBolibar** [comment]
`DiffEqSensitivity-Review` sounds good to me. It is aligned with the SciML package name, so it would make sense.
