### ISSUE TITLE
Add plain language summary 

### ISSUE THREAD

**Issue by facusapienza21** [ODINN-SciML/DiffEqSensitivity-Review#26]
This should for example introduce the notion of gradient/sensitivity and explain with respect to what are we interested in computing gradients (model parameter, states, etc)

**Comment by facusapienza21** [comment]
@JordiBolibar do you think you can give a first iteration to this? I think you can give it a good approach that is no too mathematical and can broadly cover the three communities we are trying to bring together.

**Comment by JordiBolibar** [comment]
I added a first version of the Plain language summary. Don't hesitate to give feedback on how to improve it.
