### ISSUE TITLE
Numerical Stability in Forward Mode for Simple ODE

### ISSUE THREAD

**Issue by facusapienza21** [ODINN-SciML/DiffEqSensitivity-Review#68]
Motivated by our last discussion, I wanted to create a simple example where is possible to see the instability of forward diff when the stepsize of the numerical solver are not adapted to control for both the errors in the solution and its derivative (implemented with dual numbers). Code can be found [here](https://github.com/ODINN-SciML/DiffEqSensitivity-Review/blob/main/code/dual_numbers/solver-tolerances.jl).

The example @ChrisRackauckas suggested was the following ODE
```math
\frac{du}{dt} = t^4
```
that I adapted to be 
```math
\frac{du}{dt} = (t - \theta)^4
```
to include parameter $\theta \geq 0$ to which we want to compute the gradient. Any RK method of order 5 will give exact solutions for this ODE, including the default `Tsit(5)`. When we use an adaptive stepsize, we can see that the stepsize increases gradually, as expected since the solver should find the exact solution for any given timestep. 
```julia
"""
    dyn!

This generates solutions u(t) = (t-θ)^5/5 that can be solved exactly with a 5th order integrator.
"""
function dyn!(du, u, p, t)
    θ = p[1]
    du .= (t .- θ).^4.0
end

p = [1.0] 

prob = ODEProblem(dyn!, u0, tspan, p)
sol  = solve(prob, Tsit5(), reltol=reltol, abstol=abstol)

# We can see that the time steps increase with non-stop
@show diff(sol.t)
```
However, when using a sensitivity method on top of the solver, I don't see the timesteps being controlled and instead the timesteps of all methods increase and also give the right sensitivity at the end of the simulation
```julia
g1 = Zygote.gradient(p -> loss(p, ForwardDiffSensitivity()), p)
@show g1

g2 = Zygote.gradient(p -> loss(p, ForwardSensitivity()), p)
@show g2

g3 = Zygote.gradient(p -> loss(p, nothing), p)
@show g3

g4 = ForwardDiff.gradient(p -> loss(p, nothing), p)
@show g4

@show grad_true(p)
```

Is this the expected behavior? I was expected either to get wrong sensitivities or get the right sensitivity at the cost of controlling more for the stepsize. My understanding is that this last option was the fix introduced after [this bug](https://github.com/SciML/SciMLSensitivity.jl/issues/273). Maybe this example is just too simple? 

Do you have any thoughts on this @frankschae @ChrisRackauckas ? With Frank we were also talking that it will be nice to include the calculation of the tolerances with and without sensitivity method.

**Comment by ChrisRackauckas** [comment]
We have things outside of standard AD which are correcting for this. Try setting in `solve` the keyword argument `internalnorm = (u,t) -> sum(abs2,u/length(u))` to turn it off.

**Comment by ChrisRackauckas** [comment]
xref https://github.com/ScientificComputingCWI/AutumnSchool2023/blob/main/presentations/uncorrected_ad.jl

**Comment by facusapienza21** [comment]
@ChrisRackauckas  I added the `internalnorm = (u,t) -> sum(abs2, u/length(u))` when using `ForwardDiffSensitivity()` and I am still getting the right gradients with 
```julia
function dyn!(du, u, p, t)
    θ = p[1]
    du .= (t .- θ).^4.0
end

g1 = Zygote.gradient(p -> solve(ODEProblem(dyn!, u0, tspan, p), 
                                Tsit5(), 
                                u0 = u0, 
                                p = p, 
                                sensealg = ForwardDiffSensitivity(), 
                                saveat = 0.1,
                                internalnorm = (u,t) -> sum(abs2, u/length(u)), 
                                callback = cb, 
                                reltol=1e-6, 
                                abstol=1e-6).u[end][1], p)
```
The example from [uncorrected_ad.jl](https://github.com/ScientificComputingCWI/AutumnSchool2023/blob/main/presentations/uncorrected_ad.jl) gives a different gradient for this case, but I am not sure why this is not happening for this other example. Maybe the ODE we suggested is not the best example? Could this be related to [this](https://docs.sciml.ai/SciMLSensitivity/stable/manual/differential_equation_sensitivities/#SciMLSensitivity.ForwardDiffSensitivity) specification for `ForwardDiffSensitivity()`?
```
An implementation of discrete forward sensitivity analysis through ForwardDiff.jl. 
When used within adjoint differentiation (i.e. via Zygote), this will cause forward differentiation 
of the solve call within the reverse-mode automatic differentiation environment.

https://docs.sciml.ai/SciMLSensitivity/stable/manual/differential_equation_sensitivities/#SciMLSensitivity.ForwardDiffSensitivity
```

**Comment by ChrisRackauckas** [comment]
Yeah the ODE I suggested earlier isn't the best case. I'll simplify and construct one over the weekend.

**Comment by facusapienza21** [comment]
@ChrisRackauckas did you have a chance to think about an example for this?

**Comment by ChrisRackauckas** [comment]
Yup here's a derivation: https://youtu.be/OyFP565kDUI?si=eBLhkE--tk3MXA3r&t=4891
